{\rtf1\ansi\ansicpg1252\cocoartf2865
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red181\green26\blue70;\red255\green255\blue255;\red31\green31\blue31;
\red14\green106\blue57;\red91\green47\blue214;\red38\green59\blue169;}
{\*\expandedcolortbl;;\cssrgb\c76863\c18824\c34510;\cssrgb\c100000\c100000\c100000;\cssrgb\c16078\c16078\c16078;
\cssrgb\c0\c48235\c28627;\cssrgb\c43529\c29804\c87059;\cssrgb\c19608\c32157\c72157;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs26 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 import\cf4 \strokec4  \{ CardContent, CardDescription, CardHeader, CardTitle \} \cf2 \strokec2 from\cf4 \strokec4  \cf5 \strokec5 "@/components/ui/card"\cf4 \strokec4 ;\cb1 \
\
\cf2 \cb3 \strokec2 export\cf4 \strokec4  \cf2 \strokec2 default\cf4 \strokec4  \cf2 \strokec2 function\cf4 \strokec4  \cf6 \strokec6 PrivacyPolicyContent\cf4 \strokec4 () \{\cb1 \
\pard\pardeftab720\partightenfactor0
\cf4 \cb3     \cf2 \strokec2 return\cf4 \strokec4  (\cb1 \
\cb3         <>\cb1 \
\cb3             <\cf7 \strokec7 CardHeader\cf4 \strokec4 >\cb1 \
\cb3                 <\cf7 \strokec7 CardTitle\cf4 \strokec4 >Okidex Privacy Policy</\cf7 \strokec7 CardTitle\cf4 \strokec4 >\cb1 \
\cb3                 <\cf7 \strokec7 CardDescription\cf4 \strokec4 >Effective Date: August 29, 2025</\cf7 \strokec7 CardDescription\cf4 \strokec4 >\cb1 \
\cb3             </\cf7 \strokec7 CardHeader\cf4 \strokec4 >\cb1 \
\cb3             <\cf7 \strokec7 CardContent\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "space-y-6 text-sm text-muted-foreground pt-4 max-h-[70vh] overflow-y-auto pr-6"\cf4 \strokec4 >\cb1 \
\cb3                 <\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\cb3                   At Okidex, we are committed to connecting founders with private investors and talent in a secure, transparent, and respectful manner. This Privacy Policy ("Policy") describes how Okidex, Inc. ("Okidex," "we," "us," or "our") collects, uses, shares, and protects your personal information when you use our mobile application, website (okidex.com), and related services (collectively, the "Services"). We respect your privacy and are dedicated to protecting your data in accordance with applicable laws, including Singapore\'92s Personal Data Protection Act 2012 (PDPA), as amended by the Personal Data Protection (Amendment) Act 2020, the General Data Protection Regulation (GDPR), the California Consumer Privacy Act (CCPA), and other relevant privacy regulations. In Singapore, we comply with the guidelines issued by the Personal Data Protection Commission (PDPC).\cb1 \
\cb3                 </\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\cb3                 <\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\cb3                   By using our Services, you consent to the practices described in this Policy. If you do not agree, please do not access or use the Services. We may update this Policy from time to time, and we will notify you of material changes via email, in-app notification, or by posting the updated Policy on our website with the new effective date. Your continued use of the Services after such changes constitutes your acceptance of the revised Policy.\cb1 \
\cb3                 </\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\
\cb3                 <\cf5 \strokec5 div\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "space-y-4"\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 h3\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "text-xl font-semibold text-foreground"\cf4 \strokec4 >1. Information We Collect</\cf5 \strokec5 h3\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\cb3                     We collect information to provide, improve, and personalize our Services, facilitate matchmaking between founders, investors, and talent, and ensure a safe environment. Under the PDPA, personal data is defined as data about an individual who can be identified from that data or in combination with other information we have or are likely to have access to. We act as the data controller for your personal data under applicable laws like the PDPA and GDPR.\cb1 \
\cb3                   </\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 h4\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "text-lg font-medium text-foreground pt-2"\cf4 \strokec4 >Information You Provide to Us</\cf5 \strokec5 h4\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 ul\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "list-disc pl-6 space-y-2"\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Registration and Profile Data:</\cf5 \strokec5 strong\cf4 \strokec4 > When you create an account, we collect your name, email address, phone number, professional title, location, and other details you provide, such as your role (e.g., founder, investor, or talent). For verification purposes, we may collect government-issued ID, selfies, or other identity documents through third-party providers to confirm your identity and prevent fraud. You are responsible for the accuracy and appropriateness of the data you choose to share or publish on your profile, including any personal or sensitive information you make publicly visible. Under the PDPA, we ensure you are notified of the purposes for collecting this data and obtain your consent where required.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Professional and Business Information:</\cf5 \strokec5 strong\cf4 \strokec4 > Founders may upload business plans, pitch decks, financial projections, resumes, or other business-related documents. Investors and talent may provide investment criteria, professional experience, skills, endorsements, or financial preferences. You can choose to include sensitive information, but we advise against posting unnecessary personal details publicly. You are responsible for any data, including business plans or financial details, that you choose to share or publish on your profile or with other users. We obtain explicit consent for processing sensitive personal data, such as financial details, as required by the PDPA.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Financial Information:</\cf5 \strokec5 strong\cf4 \strokec4 > If you link payment methods for premium features or transactions (e.g., subscription fees), we collect payment details such as credit/debit card numbers, bank account information, billing address, and transaction history. For matchmaking involving investments, we may collect or infer financial data with your explicit consent, such as investment history or funding requirements, in compliance with the PDPA\'92s Consent Obligation.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Communications and Content:</\cf5 \strokec5 strong\cf4 \strokec4 > Messages, connection requests, feedback, and any content you post or share through the Services, including in matches, chats, or forums. You are responsible for the content you share or publish in these interactions.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Linked Accounts:</\cf5 \strokec5 strong\cf4 \strokec4 > If you connect third-party accounts (e.g., LinkedIn, Google, or financial apps), we collect data like profile information, contacts, or professional networks, subject to your authorization and PDPA\'92s Notification Obligation.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                   </\cf5 \strokec5 ul\cf4 \strokec4 >\cb1 \
\
\cb3                   <\cf5 \strokec5 h4\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "text-lg font-medium text-foreground pt-2"\cf4 \strokec4 >Information We Collect Automatically</\cf5 \strokec5 h4\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 ul\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "list-disc pl-6 space-y-2"\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Usage Data:</\cf5 \strokec5 strong\cf4 \strokec4 > Device information (e.g., IP address, browser type, operating system), log data (e.g., pages viewed, time spent), and interaction data (e.g., matches made, searches performed).</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Location Data:</\cf5 \strokec5 strong\cf4 \strokec4 > Approximate or precise location (via GPS, IP, or device settings) to facilitate local matchmaking, with options to control this in your device settings. Under the PDPA, we notify you of location data collection purposes and obtain consent where required.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Cookies and Similar Technologies:</\cf5 \strokec5 strong\cf4 \strokec4 > We use cookies, pixels, web beacons, and other tracking technologies to recognize you across devices, analyze usage, and personalize content. For details, see our Cookie Policy below, which complies with the PDPA\'92s transparency requirements.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                   </\cf5 \strokec5 ul\cf4 \strokec4 >\cb1 \
\
\cb3                    <\cf5 \strokec5 h4\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "text-lg font-medium text-foreground pt-2"\cf4 \strokec4 >Information from Others</\cf5 \strokec5 h4\cf4 \strokec4 >\cb1 \
\cb3                    <\cf5 \strokec5 ul\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "list-disc pl-6 space-y-2"\cf4 \strokec4 >\cb1 \
\cb3                       <\cf5 \strokec5 li\cf4 \strokec4 >Data from matches or connections (e.g., endorsements, referrals, or shared business plans).</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                       <\cf5 \strokec5 li\cf4 \strokec4 >Aggregated or anonymized data from partners for analytics, ensuring compliance with the PDPA\'92s Protection Obligation.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                    </\cf5 \strokec5 ul\cf4 \strokec4 >\cb1 \
\cb3                    <\cf5 \strokec5 p\cf4 \strokec4 >We do not collect information from children under 18, and our Services are not intended for them (see Section 8). The PDPA does not apply to business contact information (e.g., name, business title, business email) or data of deceased individuals (for over 10 years), and we align our practices accordingly.</\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\cb3                 </\cf5 \strokec5 div\cf4 \strokec4 >\cb1 \
\cb3                 \cb1 \
\cb3                 <\cf5 \strokec5 div\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "space-y-4"\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 h3\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "text-xl font-semibold text-foreground"\cf4 \strokec4 >2. How We Use Your Information</\cf5 \strokec5 h3\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 p\cf4 \strokec4 >We use your information to operate and enhance our Services, based on legal grounds such as your consent, contractual necessity, legitimate interests (e.g., fraud prevention), or legal obligations, as permitted under the PDPA, GDPR, and other laws.</\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 ul\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "list-disc pl-6 space-y-2"\cf4 \strokec4 >\cb1 \
\cb3                         <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Providing and Personalizing Services:</\cf5 \strokec5 strong\cf4 \strokec4 > To create profiles, suggest matches (e.g., connecting founders with compatible investors or talent based on profiles, location, and algorithms), facilitate communications, and enable features like virtual meetings or document sharing, in line with the PDPA\'92s Purpose Limitation Obligation.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                         <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Matchmaking and Networking:</\cf5 \strokec5 strong\cf4 \strokec4 > Analyze professional data, business plans, and financial preferences to predict compatibility and recommend opportunities, with your explicit consent for sharing sensitive details like financial information or business plans during matches, as required by the PDPA\'92s Consent Obligation.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                         <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Safety and Security:</\cf5 \strokec5 strong\cf4 \strokec4 > Verify identities, monitor for violations of our terms, detect fraud (e.g., using transaction patterns or automated systems), and prevent unauthorized access, fulfilling the PDPA\'92s Protection Obligation.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                         <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Payments and Financial Services:</\cf5 \strokec5 strong\cf4 \strokec4 > Process transactions, manage subscriptions, and, with explicit consent, facilitate investment-related disclosures (e.g., sharing funding needs with investors).</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                         <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Communications:</\cf5 \strokec5 strong\cf4 \strokec4 > Send service updates, security alerts, and promotional messages (e.g., about new features or events), with opt-out options for marketing in compliance with the PDPA\'92s Do Not Call (DNC) Registry provisions.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                         <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Analytics and Improvement:</\cf5 \strokec5 strong\cf4 \strokec4 > Conduct research, develop insights (e.g., workforce trends in startups), and improve algorithms, using aggregated data where possible, as permitted under the PDPA\'92s Accountability Obligation.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                         <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Advertising and Marketing:</\cf5 \strokec5 strong\cf4 \strokec4 > Target ads based on your interests and usage, without sharing personal data with advertisers except in hashed form or with consent, ensuring compliance with the PDPA\'92s Notification Obligation.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                         <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Compliance and Legal Purposes:</\cf5 \strokec5 strong\cf4 \strokec4 > Fulfill legal requirements, such as anti-money laundering (AML) checks, tax reporting, or responding to authorities, as required by the PDPA and other laws.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                     </\cf5 \strokec5 ul\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 p\cf4 \strokec4 >For sensitive data like financial information or business plans, we require your explicit consent before processing or sharing, which you can withdraw at any time via account settings, as supported by the PDPA\'92s consent withdrawal provisions.</\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\cb3                 </\cf5 \strokec5 div\cf4 \strokec4 >\cb1 \
\
\cb3                 <\cf5 \strokec5 div\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "space-y-4"\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 h3\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "text-xl font-semibold text-foreground"\cf4 \strokec4 >3. Sharing Your Information</\cf5 \strokec5 h3\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 p\cf4 \strokec4 >We share your information only as necessary and with safeguards in place, such as contracts requiring data protection, in compliance with the PDPA\'92s Transfer Limitation Obligation.</\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 ul\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "list-disc pl-6 space-y-2"\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >With Other Users:</\cf5 \strokec5 strong\cf4 \strokec4 > In matches, we share profile details, business plans, or financial information you consent to disclose (e.g., a founder sharing a pitch deck with an investor). You control visibility through privacy settings. You are responsible for the data you choose to share with other users, including in profiles, messages, or matchmaking interactions. We ensure compliance with the PDPA\'92s Consent and Notification Obligations before sharing.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Service Providers:</\cf5 \strokec5 strong\cf4 \strokec4 > With third-party vendors (data intermediaries under the PDPA) for functions like payment processing (e.g., Stripe), identity verification, cloud storage, analytics, or customer support. These providers are bound by strict confidentiality and data protection agreements, meeting the PDPA\'92s requirements for data intermediaries.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Affiliates and Partners:</\cf5 \strokec5 strong\cf4 \strokec4 > Within our corporate group or with financial partners for fraud prevention or service enhancement, ensuring equivalent privacy protections as required by the PDPA.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >For Legal Reasons:</\cf5 \strokec5 strong\cf4 \strokec4 > To comply with laws, prevent harm, enforce terms, or in response to subpoenas, with discretion to disclose if we believe it\'92s necessary, as permitted under the PDPA.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Business Transfers:</\cf5 \strokec5 strong\cf4 \strokec4 > In mergers, acquisitions, or asset sales, your data may be transferred, with notice provided, in line with PDPA guidelines.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Aggregated Data:</\cf5 \strokec5 strong\cf4 \strokec4 > Non-identifiable insights shared for research or marketing, ensuring no personal data is disclosed.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                   </\cf5 \strokec5 ul\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 p\cf4 \strokec4 >We do not sell your personal data. For financial information, sharing requires your explicit consent, and we use mechanisms like standard contractual clauses for international transfers to ensure a comparable level of protection as required by the PDPA\'92s Transfer Limitation Obligation.</\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\cb3                 </\cf5 \strokec5 div\cf4 \strokec4 >\cb1 \
\
\cb3                 <\cf5 \strokec5 div\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "space-y-4"\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 h3\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "text-xl font-semibold text-foreground"\cf4 \strokec4 >4. Cookie Policy</\cf5 \strokec5 h3\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 p\cf4 \strokec4 >We use cookies and similar technologies (e.g., web beacons, pixels, and device identifiers) to enhance your experience, analyze usage, and deliver personalized content. This Cookie Policy, aligned with PDPA guidelines, explains how we use these technologies and your choices.</\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\cb3                    <\cf5 \strokec5 h4\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "text-lg font-medium text-foreground pt-2"\cf4 \strokec4 >Types of Cookies We Use</\cf5 \strokec5 h4\cf4 \strokec4 >\cb1 \
\cb3                    <\cf5 \strokec5 ul\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "list-disc pl-6 space-y-2"\cf4 \strokec4 >\cb1 \
\cb3                       <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Essential Cookies:</\cf5 \strokec5 strong\cf4 \strokec4 > Necessary for the Services to function, such as maintaining your login session, securing your account, and enabling core features like matchmaking. These cannot be disabled, as they are critical to service delivery.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                       <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Performance Cookies:</\cf5 \strokec5 strong\cf4 \strokec4 > Collect anonymized data on how you use our Services (e.g., pages visited, time spent) to improve performance and user experience. Examples include Google Analytics cookies.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                       <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Functionality Cookies:</\cf5 \strokec5 strong\cf4 \strokec4 > Enable enhanced features, like remembering your preferences (e.g., language or location settings) or customizing your interface.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                       <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Advertising Cookies:</\cf5 \strokec5 strong\cf4 \strokec4 > Used to deliver relevant ads and track ad performance. We may share hashed, non-identifiable data with ad partners to personalize ads across devices, with your consent.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                       <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Social Media Cookies:</\cf5 \strokec5 strong\cf4 \strokec4 > Allow integration with platforms like LinkedIn for account linking or sharing, subject to your consent and the third party\'92s privacy policy.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                    </\cf5 \strokec5 ul\cf4 \strokec4 >\cb1 \
\cb3                    <\cf5 \strokec5 h4\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "text-lg font-medium text-foreground pt-2"\cf4 \strokec4 >How We Use Cookies</\cf5 \strokec5 h4\cf4 \strokec4 >\cb1 \
\cb3                    <\cf5 \strokec5 ul\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "list-disc pl-6 space-y-2"\cf4 \strokec4 >\cb1 \
\cb3                       <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Authentication:</\cf5 \strokec5 strong\cf4 \strokec4 > Recognize you when you log in and ensure secure access.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                       <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Personalization:</\cf5 \strokec5 strong\cf4 \strokec4 > Tailor match suggestions and content based on your interactions and profile.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                       <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Analytics:</\cf5 \strokec5 strong\cf4 \strokec4 > Measure traffic, identify popular features, and optimize Services.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                       <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Advertising:</\cf5 \strokec5 strong\cf4 \strokec4 > Show targeted ads on and off our Services, ensuring relevance without sharing personal data directly with advertisers.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                    </\cf5 \strokec5 ul\cf4 \strokec4 >\cb1 \
\cb3                    <\cf5 \strokec5 h4\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "text-lg font-medium text-foreground pt-2"\cf4 \strokec4 >Managing Cookies</\cf5 \strokec5 h4\cf4 \strokec4 >\cb1 \
\cb3                    <\cf5 \strokec5 p\cf4 \strokec4 >Under the PDPA, we notify you of cookie usage purposes and obtain consent for non-essential cookies. You can control cookies through:</\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\cb3                    <\cf5 \strokec5 ul\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "list-disc pl-6 space-y-2"\cf4 \strokec4 >\cb1 \
\cb3                       <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Cookie Consent Banner:</\cf5 \strokec5 strong\cf4 \strokec4 > On your first visit, choose which non-essential cookies to allow. Update preferences anytime via the "Manage Cookies" link at okidex.com/cookies.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                       <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Browser Settings:</\cf5 \strokec5 strong\cf4 \strokec4 > Block or delete cookies, though this may affect functionality (e.g., logging you out). Instructions are available for browsers like Chrome, Firefox, or Safari.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                       <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Device Settings:</\cf5 \strokec5 strong\cf4 \strokec4 > Adjust tracking settings (e.g., \'93Limit Ad Tracking\'94 on iOS or \'93Opt Out of Ads Personalization\'94 on Android).</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                       <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Third-Party Opt-Outs:</\cf5 \strokec5 strong\cf4 \strokec4 > Visit sites like youronlinechoices.eu (EU) or optout.networkadvertising.org (US) for ad network opt-outs.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                    </\cf5 \strokec5 ul\cf4 \strokec4 >\cb1 \
\cb3                    <\cf5 \strokec5 h4\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "text-lg font-medium text-foreground pt-2"\cf4 \strokec4 >Third-Party Cookies</\cf5 \strokec5 h4\cf4 \strokec4 >\cb1 \
\cb3                    <\cf5 \strokec5 p\cf4 \strokec4 >Some cookies are set by partners (e.g., analytics or ad providers). These are governed by their privacy policies, and we ensure they meet PDPA standards. For example, Google Analytics uses anonymized data, and we do not share identifiable information with ad partners without consent.</\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\cb3                    <\cf5 \strokec5 p\cf4 \strokec4 >We retain cookie data for up to 13 months, unless required for legal purposes or deleted earlier at your request, in line with the PDPA\'92s Retention Limitation Obligation. For more details, contact us at wilfred@okidex.com.</\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\cb3                 </\cf5 \strokec5 div\cf4 \strokec4 >\cb1 \
\
\cb3                 <\cf5 \strokec5 div\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "space-y-4"\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 h3\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "text-xl font-semibold text-foreground"\cf4 \strokec4 >5. Data Security and Retention</\cf5 \strokec5 h3\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 p\cf4 \strokec4 >We implement reasonable security measures, including encryption, firewalls, and access controls, to protect against unauthorized access, loss, or misuse, fulfilling the PDPA\'92s Protection Obligation. However, no system is completely secure, so we cannot guarantee absolute security.</\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 p\cf4 \strokec4 >We retain data as needed for the purposes described, in compliance with the PDPA\'92s Retention Limitation Obligation:</\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 ul\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "list-disc pl-6 space-y-2"\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Profile data:</\cf5 \strokec5 strong\cf4 \strokec4 > Until account deletion, plus up to 28 days for restoration.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Financial and transaction data:</\cf5 \strokec5 strong\cf4 \strokec4 > For audit, tax, or legal purposes (e.g., 7 years).</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Verification data:</\cf5 \strokec5 strong\cf4 \strokec4 > Up to 3 years for fraud prevention.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Cookie data:</\cf5 \strokec5 strong\cf4 \strokec4 > Up to 13 months, as noted above.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                   </\cf5 \strokec5 ul\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 p\cf4 \strokec4 >Upon account deletion, we anonymize or delete data, though shared content may remain visible to others. You can request deletion via settings, as supported by the PDPA\'92s Access and Correction Obligation.</\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 p\cf4 \strokec4 >In the event of a data breach likely to result in significant harm or affecting a significant number of individuals, we will notify the PDPC and affected individuals within 3 calendar days of assessment, as required by the PDPA\'92s Data Breach Notification Obligation.</\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\cb3                 </\cf5 \strokec5 div\cf4 \strokec4 >\cb1 \
\
\cb3                 <\cf5 \strokec5 div\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "space-y-4"\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 h3\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "text-xl font-semibold text-foreground"\cf4 \strokec4 >6. Your Rights and Choices</\cf5 \strokec5 h3\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 p\cf4 \strokec4 >We empower you to control your data, in line with the PDPA, GDPR, and CCPA:</\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 ul\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "list-disc pl-6 space-y-2"\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Access and Correction:</\cf5 \strokec5 strong\cf4 \strokec4 > View, edit, or export your information via account settings. Under the PDPA, you can request access to your personal data and information about its use or disclosure within the past year, and request corrections to errors or omissions.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Deletion:</\cf5 \strokec5 strong\cf4 \strokec4 > Request data deletion, subject to legal retention requirements, as supported by the PDPA.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Opt-Outs:</\cf5 \strokec5 strong\cf4 \strokec4 > Withdraw consent for marketing, location sharing, cookies, or data processing (e.g., for matching algorithms) at any time, with notification of consequences as required by the PDPA.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Do Not Sell/Share:</\cf5 \strokec5 strong\cf4 \strokec4 > Under CCPA, opt out of data sales (though we do not sell data).</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >GDPR and PDPA Rights:</\cf5 \strokec5 strong\cf4 \strokec4 > If in the EU/EEA/UK or Singapore, exercise rights to access, rectify, erase, restrict, or object to processing, or data portability. For Singapore residents, contact the PDPC for complaints about data misuse.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Cookie Controls:</\cf5 \strokec5 strong\cf4 \strokec4 > Manage via the Cookie Consent Banner, browser settings, or our Cookie Policy page.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Financial Consent:</\cf5 \strokec5 strong\cf4 \strokec4 > Specifically revoke consent for sharing financial info or business plans.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >DNC Registry:</\cf5 \strokec5 strong\cf4 \strokec4 > Opt out of telemarketing by registering your Singapore telephone number with the PDPA\'92s Do Not Call Registry.</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                   </\cf5 \strokec5 ul\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 p\cf4 \strokec4 >To exercise rights, contact our Data Protection Officer (DPO), as required by the PDPA\'92s Accountability Obligation, at wilfred@okidex.com. We respond within applicable timeframes (e.g., 30 days under CCPA and PDPA). For complaints, Singapore residents can contact the PDPC at 10 Pasir Panjang Road, #03-01, Mapletree Business City, Singapore 117438.</\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\cb3                 </\cf5 \strokec5 div\cf4 \strokec4 >\cb1 \
\
\cb3                 <\cf5 \strokec5 div\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "space-y-4"\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 h3\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "text-xl font-semibold text-foreground"\cf4 \strokec4 >7. International Data Transfers</\cf5 \strokec5 h3\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 p\cf4 \strokec4 >We operate globally and may transfer data to countries outside your residence, including the US. For transfers outside Singapore, we ensure the recipient provides a comparable level of protection as required by the PDPA\'92s Transfer Limitation Obligation, using mechanisms like standard contractual clauses or binding corporate rules, which also align with GDPR requirements.</\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\cb3                 </\cf5 \strokec5 div\cf4 \strokec4 >\cb1 \
\
\cb3                 <\cf5 \strokec5 div\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "space-y-4"\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 h3\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "text-xl font-semibold text-foreground"\cf4 \strokec4 >8. Children's Privacy</\cf5 \strokec5 h3\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 p\cf4 \strokec4 >Our Services are for users 18 and older. We do not knowingly collect data from children under 18. If we learn of such collection, we will delete it promptly, in line with the PDPA. Parents can contact us for assistance.</\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\cb3                 </\cf5 \strokec5 div\cf4 \strokec4 >\cb1 \
\
\cb3                 <\cf5 \strokec5 div\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "space-y-4"\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 h3\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "text-xl font-semibold text-foreground"\cf4 \strokec4 >9. Changes to This Policy</\cf5 \strokec5 h3\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 p\cf4 \strokec4 >We may update this Policy to reflect changes in our practices or laws. We will notify you of significant changes via email, in-app notification, or by posting the updated Policy, as required by the PDPA\'92s Accountability Obligation.</\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\cb3                 </\cf5 \strokec5 div\cf4 \strokec4 >\cb1 \
\
\cb3                 <\cf5 \strokec5 div\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "space-y-4"\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 h3\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "text-xl font-semibold text-foreground"\cf4 \strokec4 >10. Contact Us</\cf5 \strokec5 h3\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 p\cf4 \strokec4 >For questions or concerns, contact our Data Protection Officer, as mandated by the PDPA, at:</\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 ul\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "list-disc pl-6 space-y-2"\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Email:</\cf5 \strokec5 strong\cf4 \strokec4 > wilfred@okidex.com</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Mail:</\cf5 \strokec5 strong\cf4 \strokec4 > Okidex, Inc., [Address], USA</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                   </\cf5 \strokec5 ul\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 p\cf4 \strokec4 >For Singapore residents, you may also contact the Personal Data Protection Commission at:</\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\cb3                    <\cf5 \strokec5 ul\cf4 \strokec4  \cf6 \strokec6 className\cf2 \strokec2 =\cf5 \strokec5 "list-disc pl-6 space-y-2"\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Address:</\cf5 \strokec5 strong\cf4 \strokec4 > 10 Pasir Panjang Road, #03-01, Mapletree Business City, Singapore 117438</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                     <\cf5 \strokec5 li\cf4 \strokec4 ><\cf5 \strokec5 strong\cf4 \strokec4 >Website:</\cf5 \strokec5 strong\cf4 \strokec4 > www.pdpc.gov.sg</\cf5 \strokec5 li\cf4 \strokec4 >\cb1 \
\cb3                   </\cf5 \strokec5 ul\cf4 \strokec4 >\cb1 \
\cb3                   <\cf5 \strokec5 p\cf4 \strokec4 >Thank you for trusting Okidex with your information. We are committed to your privacy as we build meaningful connections in the startup ecosystem, in full compliance with the PDPA and other applicable laws.</\cf5 \strokec5 p\cf4 \strokec4 >\cb1 \
\cb3                 </\cf5 \strokec5 div\cf4 \strokec4 >\cb1 \
\cb3             </\cf7 \strokec7 CardContent\cf4 \strokec4 >\cb1 \
\cb3         </>\cb1 \
\cb3     );\cb1 \
\cb3 \}\cb1 \
\
}